# Generated by Django 4.0.5 on 2022-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(choices=[('engine_1', 'engine_1'), ('engine_2', 'engine_2'), ('engine_3', 'engine_3'), ('engine_4', 'engine_4')], max_length=50, null=True)),
                ('classification_model', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True)),
                ('time_zone', models.CharField(choices=[('usa', 'usa'), ('in', 'in'), ('uk', 'uk')], max_length=50, null=True)),
                ('process_sla', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True)),
                ('pre_processing', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True)),
                ('process_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
