# Generated by Django 4.0.5 on 2022-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0002_process_data_delete_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_data',
            name='classification_model',
            field=models.CharField(choices=[(1, 'yes'), (0, 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='pipeline',
            field=models.CharField(choices=[(0, 'engine_1'), (1, 'engine_2'), (2, 'engine_3'), (4, 'engine_4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='pre_processing',
            field=models.CharField(choices=[(0, 'pre1'), (1, 'pre2'), (2, 'pre3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='process_sla',
            field=models.CharField(choices=[(0, '1'), (1, '2'), (2, '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='time_zone',
            field=models.CharField(choices=[(0, 'usa'), (1, 'in'), (2, 'uk')], max_length=50, null=True),
        ),
    ]
