# Generated by Django 4.0.5 on 2022-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0003_alter_process_data_classification_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnn_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Regular_Model', 'Regular_Model'), ('VCG_Model', 'VCG_Model')], max_length=50, null=True)),
                ('activation', models.CharField(choices=[('relu', 'relu'), ('esl', 'esl')], max_length=50, null=True)),
                ('test_size', models.CharField(choices=[('05', '05'), ('06', '06'), ('07', '07'), ('08', '08')], max_length=50, null=True)),
                ('epochs', models.CharField(choices=[('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=50, null=True)),
                ('Batch', models.CharField(choices=[('16', '16'), ('32', '32'), ('64', '64')], max_length=50, null=True)),
                ('kernel_Initializer', models.CharField(choices=[('16', '16'), ('32', '32'), ('64', '64')], max_length=50, null=True)),
                ('optimize', models.CharField(choices=[('rmsprop', 'rmsprop'), ('xrmprop', 'xrmprop')], max_length=50, null=True)),
                ('cofidence_number', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='process_data',
            name='classification_model',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='pipeline',
            field=models.CharField(choices=[('Engine-1', 'engine_1'), ('Engine-2', 'engine_2'), ('Engine-3', 'engine_3'), ('Engine-4', 'engine_4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='pre_processing',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='process_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='process_sla',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process_data',
            name='time_zone',
            field=models.CharField(choices=[('usa', 'usa'), ('in', 'in'), ('uk', 'uk')], max_length=50, null=True),
        ),
    ]
