# Generated by Django 4.0.5 on 2022-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0005_alter_cnn_model_kernel_initializer'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_data',
            name='Input_documents',
            field=models.CharField(choices=[('JPG', 'JPG'), ('PDF', 'PDF'), ('JPEG', 'JPEG'), ('TIF', 'TIF'), ('PNG', 'PNG')], max_length=50, null=True),
        ),
    ]
