# Generated by Django 4.0.5 on 2022-06-24 06:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0006_process_data_input_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_data',
            name='Input_documents',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JPG', 'JPG'), ('PDF', 'PDF'), ('JPEG', 'JPEG'), ('TIF', 'TIF'), ('PNG', 'PNG')], max_length=50, null=True),
        ),
    ]
