# Generated by Django 4.0.5 on 2022-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0008_alter_process_data_input_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnn_model',
            name='cnnclass',
            field=models.CharField(default='Single Class', max_length=50, null=True),
        ),
    ]
