# Generated by Django 4.0.5 on 2022-06-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0010_alter_cnn_model_cnnclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnn_model',
            name='cnnclass',
        ),
    ]
