# Generated by Django 4.0.5 on 2022-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0011_remove_cnn_model_cnnclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnn_model',
            name='cnnclass',
            field=models.CharField(default='Single_Class', max_length=50),
        ),
    ]
