# Generated by Django 4.0.5 on 2022-06-24 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0012_cnn_model_cnnclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnn_model',
            name='cv_file',
            field=models.FileField(null=True, upload_to='resume', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
