# Generated by Django 4.0.5 on 2022-06-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0013_cnn_model_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnn_model',
            name='cv_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
