# Generated by Django 4.0.5 on 2022-06-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0014_alter_cnn_model_cv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnn_model',
            old_name='cv_file',
            new_name='sample_file',
        ),
    ]
