# Generated by Django 4.0.5 on 2022-06-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0015_rename_cv_file_cnn_model_sample_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnn_model',
            old_name='sample_file',
            new_name='cv_file',
        ),
    ]
