# Generated by Django 4.0.5 on 2022-06-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0016_rename_sample_file_cnn_model_cv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnn_model',
            old_name='cv_file',
            new_name='sample_file',
        ),
    ]
